spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_example?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai
    username: root
    password: Myroot123!
# //北京时间==东八区时间！=北京当地时间
# serverTimezone=GMT%2B8
# //或者使用上海时间
# serverTimezone=Asia/Shanghai
