spring:
  profiles:
    active: dev
  application:
     name: springboot-jsp-mybatis-druid
  banner:
    charset: UTF-8
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


  #连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      maxWait: 100000
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  ## jsp 配置
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
    enabled: false


logging:
  config: classpath:logback.xml
  # level: debug
  # org.springframework.boot.autoconfigure: error


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.destiny.horse
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
# 项目启动方式
debug: false
server:
  port: 8081

