spring:
  profiles:
    active: dev
  application:
     name: springboot-nacos-dubbo-provider
  #连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      maxWait: 100000
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  ## 配置单个上传文件大小
  mvc:
    static-path-pattern: /static/**
  freemarker:
    request-context-attribute: req  #req访问request
    content-type: text/html
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
    #后缀名
    suffix: .ftl
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小 10MB 设置总上传大小 100MB
      max-file-size: 10MB
      max-request-size: 100MB


  # 服务模块
  devtools:
    remote:
      restart:
        # 热部署开关
        enabled: false
logging:
  # config: classpath:logback.xml
  level:
     root: info


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.destiny.lobster.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true


server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 300
      min-spare: 30

nacos:
   config:
      server-addr: 127.0.0.1:8848
      encode: UTF-8
      # 重试次数
      max-retry: 10
      # 重试时间
      config-retry-time: 1000
      # 主配置 配置监听长轮询超时时间
      config-long-poll-timeout: 10000
      # 是否 nacos 配置优先
      remote-first: false
      group: DEFAULT_GROUP
      data-id: data-example
      type: yaml
      # 自动开启刷新
      auto-refresh: true
      # namespace:
      # username:
      # password:
      # context-path:
      namespace:

# dubbo nacos 注册地址
dubbo:
  registry:
    address: nacos://${nacos.config.server-addr}?namespace=5fa720d5-1f62-4d6d-8846-7a06489c6a5f
    timeout: 10000
    # namespace=5fa720d5-1f62-4d6d-8846-7a06489c6a5f
    # parameters:
    #   namespace: 5fa720d5-1f62-4d6d-8846-7a06489c6a5f
    # protocol: nacos
  application:
    name: lobster
    # qos-enable: false
    # qos-accept-foreign-ip: false
  provider:
    register: true
    # serialization:
    # server
    version: 1.0
    retries: 2

  protocol:
    name: dubbo
    port: 20880
    # 传输的大小
    # payload:
  scan:
    base-packages: com.destiny.lobster.service.api
