
spring:
  datasource:
    dynamic:
      allowed-public-only: true
      datasource:
        master:
          username: root
          password: Myroot123!
          url: jdbc:mysql://localhost:3306/springboot_example?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          # schema: db/schema.sql
          p6spy: true # 如果这个库不需要可单独关闭。
        slave_1:
          username: root
          password: Myroot123!
          url: jdbc:mysql://localhost:3306/springboot_example?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
          driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9790
