

spring:
    jpa:
      database: MySQL
      show-sql: true
    datasource:
      username: root
      password: 123456
      hikari:
        idle-timeout: 300000
        maximum-pool-size: 30000

      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/hotel?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
