
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    primary:
      username: root
      password: Myroot123!
      jdbc-url: jdbc:mysql://localhost:3306/springboot_example?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: primary-pool
      maximum-pool-size: 300
      minimum-idle: 2
      connection-timeout: 50000
      max-lifetime: 3000
      connection-test-query: select 1
      idle-timeout: 3000
      # schema: db/schema.sql
      # driver-class-name: com.mysql.cj.jdbc.Driver# 如果这个库不需要可单独关闭。
    second:
      username: root
      password: Myroot123!
      jdbc-url: jdbc:mysql://10.231.128.148:3306/springboot_example?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: second-pool
      maximum-pool-size: 300
      minimum-idle: 2
      connection-timeout: 50000
      max-lifetime: 3000
      connection-test-query: select 1
      idle-timeout: 3000
server:
  port: 9897

xxl:
  job:
    accessToken:
    executor:
      appname: demo-account
      port: 8088
      logretentiondays: -1
      logpath: ./jobhandler
      # 可以配置为某一台机器ip
      ip:

    admin:
      addresses: http://127.0.0.1:8081