spring:
  profiles:
    active: dev
  application:
     name: springboot-thymeleaf-mybatisplus-hikari
     version: 1.0

  #连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      auto-commit: false
      idle-timeout: 2000
      max-lifetime: 2000
      login-timeout: 200
      maximum-pool-size: 2000
      # transaction-isolation:

  ## 配置单个上传文件大小
  mvc:
    static-path-pattern: /static/**
  freemarker:
    request-context-attribute: req  #req访问request
    content-type: text/html
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
    #后缀名
    suffix: .ftl
  banner:
    location: banner.txt
    charset: UTF-8
    image:
      height: 34

logging:
  level:
    root: debug
    #org: info
    #sun: info
    com.destiny: debug
    #com: info
    #mybatis: debug
    #main.blog.mapper: debug
    #com.destiny.rabbit.mapper: debug
  # config: classpath:bak/logback-back.xml
  file:
    path: temp_logs


#公共配置与profiles选择无关
mybatis-plus:
  global-config:
    db-config:
      capital-mode: true
      id-type: id_worker
    banner: true
    # meta-object-handler: com.destiny.rabbit.config.RabbitObjFieldHandler
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.destiny.rabbit.entity
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    default-executor-type: batch
    lazy-loading-enabled: false
    # 以实际参数名去查询参数
    use-actual-param-name: true
    log-prefix: "mybatis-plus"
    # 默认获取数据条数
    default-fetch-size: 100
    default-statement-timeout: 10000
    # interceptors:
    #    - com.destiny.rabbit.config.plugins.RabbitMyBatisPlusInterceptor
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-handlers-package: com.destiny.rabbit.config.typehandler
  executor-type: batch

server:
  port: 8990
  tomcat:
    # 最大最小的工作线程数量
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    uri-encoding: UTF-8
    connection-timeout: 300s
    max-http-form-post-size: 4MB
    max-connections: 8192
    basedir: ./test
