server:
  port: 9890
  tomcat:
    uri-encoding: UTF-8


mybatis-plus:
  global-config:
    banner: true
    db-config:
      capital-mode: true
      id-type: auto
      update-strategy: NOT_NULL
      insert-strategy: NOT_NULL

  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.destiny.origin.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_victory?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: 123456
    # password: Myroot123!
    hikari:
      idle-timeout: 300
      connection-test-query: select 1
      pool-name: hikari-pool
      connection-timeout: 3000

app:
  info:
    name : 小明12
    age: 12
    birthday: 2022-01-22
    weight: 23.4
    height: 32
    user_pets:
      - dog
      - cat
    user_ext:
      learn: maths
      hobby: runing
    money: 23

