server:
  port: 9890
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  global-config:
    banner: true
    db-config:
      capital-mode: true
      id-type: auto
      update-strategy: NOT_NULL
      insert-strategy: NOT_NULL

  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.destiny.origin.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    use-actual-param-name: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_example?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: Myroot123!
    hikari:
      # 连接最大存活时间 默认 10分钟
      idle-timeout: 600000
      connection-test-query: select 1
      pool-name: hikari-
      # 连接超时时间 默认 30s
      connection-timeout: 30000
      #jdbc-url: ${spring.datasource.url}
      #username: ${spring.datasource.username}
      #password: ${spring.datasource.password}
      #driver-class-name: ${spring.datasource.driver-class-name}
      # 连接池中的最长生命周期，0 为无限长
      max-lifetime: 1800000
      # 连接池最大数
      maximum-pool-size: 20

  profiles:
    active: dev



app:
  info:
    name: 小明12
    age: 12
    birthday: 2022-01-22
    weight: 23.4
    height: 32
    user_pets:
    - dog
    - cat
    user_ext:
      learn: maths
      hobby: runing
    money: 23

# 日志配置
logging:
  level:
    com.destiny.origin.mapper : debug

