spring:
  profiles:
    active: dev
  application:
     name: springboot-nacos-dubbo-consumer

  #连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      maxWait: 100000
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  ## 配置单个上传文件大小
  mvc:
    static-path-pattern: /static/**
  freemarker:
    request-context-attribute: req  #req访问request
    content-type: text/html
    enabled: true
    #缓存配置
    cache: false
    #模板加载路径 按需配置
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      #数字格式化，无小数点
      number_format: '0.##'
    #后缀名
    suffix: .ftl
  main:
    allow-bean-definition-overriding: true

logging:
  # config: classpath:logback.xml
  level:
     root: info



#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.destiny.shrimp.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

dubbo:
  registry:
    address: nacos://127.0.0.1:8848?namespace=5fa720d5-1f62-4d6d-8846-7a06489c6a5f
    timeout: 10000
    # parameters:
    #   namespace: 5fa720d5-1f62-4d6d-8846-7a06489c6a5f
    # protocol: nacos
  application:
    name: shrimp
    # qos-enable: false
    # qos-accept-foreign-ip: false
    # provider:
    #   register: true
    # serialization:
    # server
    version: 1.0
  protocol:
    name: dubbo
    port: -1
    threads: 200
  consumer:
    check: false

server:
  port: 9090


