server:
  port: 8090

## https://blog.csdn.net/weixin_44030218/article/details/86777664
spring:
  application:
    name: springboot-es
  data:
    elasticsearch:
      cluster-name: acedata
      cluster-nodes: 192.168.111.36:9300
