spring:
  profiles:
    active: dev
  application:
     name: springboot-thymeleaf
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false
server:
  port: 8970
