spring:
  elasticsearch:
    password: password
    username: username
    connection-timeout: 100000
    use-ssl: false
    max-in-memory-size: 20000
    socket-timeout: 100000
    endpoints: ip:port

redisson:
  address: redis://localhost:6379
  password: xxx
