spring:
    elasticsearch:
        password: elastic@admin
        username: elastic
        connection-timeout: 100000
        use-ssl: false
        max-in-memory-size: 20000
        socket-timeout: 100000
        endpoints: 172.18.30.54:9200

redisson:
   address: redis://123.57.63.12:6579
   password: tianhe
