ex
spring:
  profiles:
    active: dev
  application:
     name: svn-demo
  banner:
    charset: UTF-8
  http:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  #连接池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      maxWait: 100000
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100

  ## jsp 配置
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


logging:
  config: classpath:logback.xml


#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.destiny.eagle
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9090
  servlet:
    context-path:
